// <auto-generated />
namespace SmithsModding_Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewsItemPostLength512 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewsItemPostLength512));
        
        string IMigrationMetadata.Id
        {
            get { return "201601262045475_NewsItem-PostLength-512"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
